### ISSUE TITLE
Binary does not compile

### ISSUE THREAD

**Issue by conrad784** [Submanifold/EtherCurve#1]
`[ 62%] Building CXX object CMakeFiles/ethercurve.dir/PacketRenderer.cpp.o
/home/conrad/git/stuff/EtherCurve/PacketRenderer.cpp: In member function ‘QGraphicsItem* PacketRenderer::render(qreal, qreal, const pcap_pkthdr*, const uchar*) const’:
/home/conrad/git/stuff/EtherCurve/PacketRenderer.cpp:136:27: error: ‘log’ is not a member of ‘std’
     relativeLength = std::log( packetHeader->len ) / std::log( _mtu );
                           ^~~
/home/conrad/git/stuff/EtherCurve/PacketRenderer.cpp:136:59: error: ‘log’ is not a member of ‘std’
     relativeLength = std::log( packetHeader->len ) / std::log( _mtu );
                                                           ^~~
make[2]: *** [CMakeFiles/ethercurve.dir/build.make:135: CMakeFiles/ethercurve.dir/PacketRenderer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/ethercurve.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

**Comment by Pseudomanifold** [comment]
Fixed, please retest and close :-)
